config/routes.rb
Rails.application.routes.draw do

    root 'pages#index'
    resources :games, only:[:new, :show]

    get 'games/:id/update', to: 'games#update_board', as: 'update_board'

end

app/models/game.rb
class Game < ActiveRecord::Base
  serialize :board

  def initialize
    super
    self.counter = 0
    self.board = Array.new(3).map{[nil, nil, nil]} 
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
    @game.save

    redirect_to game_path(@game)
  end
  
  def update_board
    @game = Game.last
    a = params[:row].to_i
    b = params[:column].to_i
    if @game.counter.even? && !@game.board[a][b]
      @game.board[a][b] = 'O'
    elsif !@game.board[a][b]
      @game.board[a][b] = 'X'
    end
    @game.counter +=1
    @game.save
    redirect_to game_path(@game)
  end

  def show
    @game = Game.last
    winning_conditions
  end

  def winning_conditions

    square1 = @game.board[0][0]
    square2 = @game.board[0][1]
    square3 = @game.board[0][2]
    square4 = @game.board[1][0]
    square5 = @game.board[1][1]
    square6 = @game.board[1][2]
    square7 = @game.board[2][0]
    square8 = @game.board[2][1]
    square9 = @game.board[2][2]

    wins = [[square1, square2, square3], [square4, square5, square6], [square7, square8, square9], [square1, square4, square7], [square2, square5, square8], [square3, square6, square9], [square1,square5, square9], [square3, square5, square7]]

    if wins.any? { |line| line.all? { |square| square == 'X' }} || wins.any? { |line| line.all? { |square| square == 'O' }}
      @winning_statement = "You won"
      @winner = ""
    elsif @game.board.any? { |array| array.include?(nil) }
      @winning_statement = "Game in session"
    else
      @winning_statement = "It's a tie"
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/show.html.erb
<!-- xo -->
<!-- xxoo -->
<table>
    <tr>
        <td><%= @game.board[0][0] %><%= link_to "Place your marker", update_board_path(:row => 0, :column => 0) unless @game.board[0][0] || @winner %></td>
        <td><%= @game.board[0][1] %><%= link_to "Place your marker", update_board_path(:row => 0, :column => 1) unless @game.board[0][1] || @winner %></td>
        <td><%= @game.board[0][2] %><%= link_to "Place your marker", update_board_path(:row => 0, :column => 2) unless @game.board[0][2] || @winner %></td>
    </tr>
    <tr>
        <td><%= @game.board[1][0] %><%= link_to "Place your marker", update_board_path(:row => 1, :column => 0) unless @game.board[1][0] || @winner %></td>
        <td><%= @game.board[1][1] %><%= link_to "Place your marker", update_board_path(:row => 1, :column => 1) unless @game.board[1][1] || @winner %></td>
        <td><%= @game.board[1][2] %><%= link_to "Place your marker", update_board_path(:row => 1, :column => 2) unless @game.board[1][2] || @winner %></td>
    </tr>
    <tr>
        <td><%= @game.board[2][0] %><%= link_to "Place your marker", update_board_path(:row => 2, :column => 0) unless @game.board[2][0] || @winner %></td>
        <td><%= @game.board[2][1] %><%= link_to "Place your marker", update_board_path(:row => 2, :column => 1) unless @game.board[2][1] || @winner %></td>
        <td><%= @game.board[2][2] %><%= link_to "Place your marker", update_board_path(:row => 2, :column => 2) unless @game.board[2][2] || @winner %></td>
    </tr>
</table>

<%= @winning_statement %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTtt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1> Hi! </hi>

<%= link_to "New Game", new_game_path %> 

<table>


</table>